//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class document
    {
        public int docsId { get; set; }
        public string DocsType { get; set; }
        public string DocsPath { get; set; }
        public Nullable<int> userId { get; set; }
        public string ImgType { get; set; }
        public string ImgPath { get; set; }
    
        public virtual mvc_tb mvc_tb { get; set; }
    }
}
